### PR TITLE
[WIP] 310 factory bot traits

### LINKED ISSUE #310: Create factory_bot traits
We have need for varied `user`, `box_request`, `box`, and `box_item` factory traits (We have existing factories) for use in tests, and later to create seed data. 

If we had `box` traits that mimic the methods in the box model such as `design_claimed`, `design_completed`, `shipping_claimed`, `shipping_completed` where the relevant `*_by_id`,`*_at`, and `aasm_state` were populated, that'd be amazing. For `user`, we need a trait for each constant in the Permission model. 

This would allow us to skip all the cajoling we had to do in `box_spec.rb`. 
Instead, it'd be so awesome to be able to call something like:
* `designer = create(:designer)` bc there was already a trait `designer` on user who had an associated `create(:user_permission, name: Permission::BOX_DESIGNER)`
* `assembled_box = create(:box, :is_assembled)`, which also has/mimics the traits  :is_designed, :is_researched, box_request#is_reviewed, etc, bc our `/box_requests` index needs all the prior lifecycle phase to be true and all future lifecycle phases to be untrue to display correctly.
* `box_item_with_research_needed = create(:box_item_research_needed)` that is a trait on box_item that who has an associated `create(:inventory_type, research_needed: true)`

You might want to check out: 
* Background doc (linked from README)
* is_reviewed, is_shipped, etc, methods in `box_rb`
* `aasm` blocks in the `box_request` and `box.rb` models
* `box_requests/index.html.erb` or `localhost:3000/box_requests` in your local browser
* `database-diagram.png`, linked from README
* `spec/models/box_spec.rb` to see how we can manually walk box_requests along in the process.

### PR DESCRIPTION
**Pull request by leosoaivan**
partially resolves #310 

### Description

Implement traits for User factory.

### Type of change
- New feature (non-breaking change which adds functionality)

### How Has This Been Tested?

- On current tests (i.e., box_spec.rb)

### CODE REVIEW

**Comment by leosoaivan** [comment]
@maebeale Just wanted to check in re: this ticket, and get your take on the traits I created for the User factory. Just wanted to make sure I was on the right track :).

**Comment by maebeale** [comment]
Yes, EXACTLY! Thank you, @leosoaivan!

**Comment by leosoaivan** [comment]
@maebeale it may take a bit of time for me to get through making traits for the other models. Would it be okay to open up this PR for the user traits for now?

**Comment by maebeale** [comment]
ABSOLUTELY, @leosoaivan! Yes, it's a very large scope of work. You'll remove the WIP from this one?

**Comment by leosoaivan** [comment]
Good to go!

**Pull request merged**
