### PR TITLE
Add draft circleci config

### LINKED ISSUE #327: Need for CI and checks in PRs
A CI with github integration in order to only allow PRs with passing tests to be merged would be greatly beneficial as a green test suite is the easiest way for someone to get quick feedback and contribute more easily and with more confidence!

I'd suggest [Gitlab CI](https://about.gitlab.com/solutions/github/) as it seems feature-proof and also acquired gemnasium - given that we have a ruby/rails project! =)

### PR DESCRIPTION
**Pull request by h-m-m**
Resolves #327 

### Description

This config will allow us to automate running the test suite for each PR. This will help ensure that all changes and new tests work on a controlled environment in addition to any developer's working environment.

### Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

### How Has This Been Tested?

The circleci history should now show up linked at the bottom of this PR, and it will show how this change has been tested.

### CODE REVIEW

**Comment by h-m-m** [comment]
This is inefficient, insufficiently organized, and not reliable enough. If I had time to dig into the docker config for the project as a whole, we could be a lot smarter about this. If I had a place to tell circleci to fetch a better docker image from, that would be nice, too.

That said it works. I mean, the tests fail, but the tests *run*, and the ones that fail are the ones that should fail given the status of the rest of the code.

**Comment by h-m-m** [comment]
@maebeale The tests don't pass. Should we make an issue to address these pending tests? Would merging this PR in without fixing those tests first confuse people, or be helpful despite the failures. Do you have an opinion on this and its priority? I'm happy to go with my gut on this, but would prefer to do so with your input

**Comment by maebeale** [comment]
@howard right. Yeah. I was wondering best move from here also. I trust your gut! (What does it say? Lol). My sense is to merge this, make the next issue to get the tests passing again, and make it the highest priority. Do you (and your gut) agree?

**Comment by h-m-m** [comment]
@maebeale That sounds right to me. I'm glad we're thinking along the same lines. Do you mind creating the relevant issue?

**Pull request merged**
