### PR TITLE
Updating navbar styles

### PR DESCRIPTION
**Pull request by geraldbcastillo**
Additional styles for  #150  

### Description

adding background color to home-nav to make uniform and adding padding to other navbar icons

### Type of change

- Style updates

### Screenshots

navbar

### CODE REVIEW

**Comment by maebeale** [comment]
@MxOliver ok to approve/merge this?

**Comment by maebeale** [comment]
Thanks @geraldbcastillo !

**Comment by maebeale** [comment]
@geraldbcastillo Any chance you could take on the other portion of the issue that includes styling of the username button?

Screen Shot 2019-10-05 at 1 18 14 PM

**Review by maebeale — APPROVED** [review]

**Comment by geraldbcastillo** [comment]
@maebeale i would love to! i wasn’t sure if there was somewhere to create credentials? or did that get set up in the initial set up? i’m really only familiar w the front end stuff 😅

**Comment by maebeale** [comment]
Ah! Yes, @geraldbcastillo, the credentials for logging in are in db/seeds.rb. the username is
currently showing next to the picture in the far right of the nav, but we
want it to show above, as in the attached photo.

**Pull request merged**
