### PR TITLE
Add rubocop to the project, run automatic fixes

### PR DESCRIPTION
**Pull request by laser-shark**
### Description

This PR adds rubocop to the project and fixes all the automatically fixable issues. This will improve code readability. If you like this PR, I will work on fixing more offenses!

### Type of change

Enhancement

### CODE REVIEW

**Comment by atzorvas** [comment]
It's hard to merge 3k LOC changes, everyone is going to have conflicts afterwards!

If merging this is an issue (@maebeale can give more insight I guess) I'd suggest breaking this PR into smaller ones

That said, I do love rubocop and I'd love to see it as an integration in the PR process as well!

Cheers

**Comment by maebeale** [comment]
> It's hard to merge 3k LOC changes, everyone is going to have conflicts afterwards!
> 
> If merging this is an issue (@maebeale can give more insight I guess) I'd suggest breaking this PR into smaller ones
> 
> That said, I do love rubocop and I'd love to see it as an integration in the PR process as well!
> 
> Cheers

Yeah, I'm with @atzorvas. Love Rubocop, but don't want to get in a failing state. @laser-shark do you have experience doing what @atzorvas recommended -- breaking this up into smaller chunks?

**Comment by maebeale** [comment]
p.s. @laser-shark thank you for submitting these! we'd love to get in line, and thank you for offering extra help to do so!

**Comment by laser-shark** [comment]
Well I could submit all 4000~ offenses individually 😁just kidding of course. Maybe a first PR could just be adding rubocop to the project without fixing anything? That way, future contributors can at least check their own work.

**Comment by atzorvas** [comment]
Adding it to the project and probably adding hound so this runs for new
changesets and comments in prs is a great first step!

**Comment by maebeale** [comment]
@laser-shark sounds great! are you able to update this PR to remove all the autofixes?
and, would you add something about utilizing rubocop in the CONTRIBUTING.rb file as part of this PR?

**Comment by maebeale** [comment]
@atzorvas i love Hound! i can add an issue for that.

**Comment by laser-shark** [comment]
@maebeale  yes I think I can do that! I'll get it done tomorrow.

**Review by maebeale — APPROVED** [review]
Perfect, @laser-shark ! Thank you!

**Pull request merged**
