### PR TITLE
Resolved Issues #239

### LINKED ISSUE #239: Add link to README.rb to CONTRIBUTING.rb
Add link to: https://github.com/rubyforgood/voices-of-consent/blob/develop/CONTRIBUTING.md on the README

### PR DESCRIPTION
**Pull request by abhushanaj**
Thanking you for letting begineer make their contribution.

Resolves #239  

### Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not
  work as expected)
- This change requires a documentation update
- Documentation update

### CODE REVIEW

**Comment by maebeale** [comment]
Thank you @abhu-A-J ! If you're willing to resolve the conflicts, I'll still approve of this PR. Thank you for jumping in. Happy Hacktoberfest!

**Comment by maebeale** [comment]
@abhu-A-J also, this doesn't resolve issue #1 -- would you remove that from the description above?

**Comment by abhushanaj** [comment]
@maebeale thanks for letting me know about it. I'm guessing its okay now? I edited the description as well as corrected the merge conflicts!

**Review by maebeale — APPROVED** [review]
Thank you, @abhu-A-J !!!

**Comment by abhushanaj** [comment]
@maebeale most welcome and thanks for letting me add something to your awesome work.

**Pull request merged**
