### PR TITLE
Update devise to 4.7.1

### LINKED ISSUE #240: Update Devise to handle GitHub alert re gem vulnerabilities
https://github.com/rubyforgood/voices-of-consent/network/alerts

### PR DESCRIPTION
**Pull request by shivamvinsol**
Resolves #240 

### Description
Updates devise gem to 4.7.1 to mitigate vulnerability issues.

### Type of change
- New feature (non-breaking change which adds functionality)

### How Has This Been Tested?
Locally tested authentication.

### CODE REVIEW

**Comment by shivamvinsol** [comment]
@maebeale This PR is ready for review.

**Review by maebeale — COMMENTED** [review]
Thank you, @shivamvinsol !!!

Did you go through the CHANGELOG (https://github.com/plataformatec/devise/blob/master/CHANGELOG.md) to see if we need to make any code changes to accommodate this upgrade?

**Comment by shivamvinsol** [comment]
@maebeale, Yes, I did go through the changelog, and it seems that all the changes are non-breaking changes, and should not hamper with our code.

**Comment by maebeale** [comment]
Thank you!

**Pull request merged**
