### PR TITLE
improving content visualization

### LINKED ISSUE #424: Add padding on Users index above and below button, and at bottom of page
Without the padding, it looks like you're not able to scroll to see the whole list/page

### PR DESCRIPTION
**Pull request by renatamarques97**
# Checklist:
- I have performed a self-review of my own code,
- New and existing unit tests pass locally with my changes ("bundle exec rake") 
ps: there is a spec failing, but it's not related to my PR.

### Description
There are a few design problems especially about content visualization, described in #424
I follow some design good practices to resolve this:
https://blog.hubspot.com/marketing/best-website-designs-list
https://www.orbitmedia.com/blog/website-footer-design-best-practices/
I think it also resolves #424

### Type of change
- Improvement

### Screenshots
Screen Shot 2020-03-22 at 18 33 44

### CODE REVIEW

**Comment by maebeale** [comment]
@renatamarques97 hello! we got our tests and the navbar thing worked out. would you be willing to rebase this against develop?

**Comment by renatamarques97** [comment]
sure @maebeale

**Comment by renatamarques97** [comment]
done! @maebeale

**Review by maebeale — APPROVED** [review]
Great! Thank you, @renatamarques97 !

**Pull request merged**
