### PR TITLE
message log dropdown # 156

### LINKED ISSUE #156: Change MessageLog form to be a dropdown
It's polymorphic, so if new, assume the messagable_type is a Person
Otherwise, hide the polymorphic type and change the id field to a dropdown

### PR DESCRIPTION
**Pull request by smoline**
Resolves #156

### Description

Converted the message_log_form into a React component. Made the polymorphic field messageable_type into a dropdown on new with a list of the person models and then expanded that to include box_request after speaking with maebeale. The messageable_ids field is also a dropdown and it populates with the ids of the type selected. While testing this, delivery_type kept me from submitting, so it is also now a drop down with the proper enums listed as options.

### Type of change

- New feature (non-breaking change which adds functionality)

### How Has This Been Tested?

Tested in the view by me. A test suite for React has not been added to the project yet.

### CODE REVIEW

**Comment by smoline** [comment]
@maebeale this one is ready for review!

**Review by maebeale — COMMENTED** [review]
Hey there, @smoline ! I've noticed a couple things when testing this code.

- It doesn't seem to be detecting IDs for anything other than those in the BoxRequest table
- If I select each one going down the line to BoxRequest, I get "no ids on this table", even when I do have data in those other tables
- When I get to BoxRequest, I see IDs. Then, when I switch the dropdown back to any other Messageable, those same IDs are in the dropdown (rather than showing the "no ids on this table")
- Ideally we'd store the ID, but display the "name" for these items. Would it be possible to make sure all Messageable models have a `def name` and call that instead?

**Comment by smoline** [comment]
@maebeale this one is ready for review again!

**Comment by maebeale** [comment]
Great work, @smoline !!!!!

**Comment by maebeale** [comment]
Thanks for going back over and refining this!

**Review by maebeale — APPROVED** [review]

**Pull request merged**
