### PR TITLE
Development environment database seeds

### LINKED ISSUE #261: Create seeds_dev.rb file with development seeds
- Create a `seeds_dev.rb` file that creates fake data (using the Faker gem we have installed) for all tables (or even most of them -- or any!)
- Add running this file to the dev:setup rake task

### PR DESCRIPTION
**Pull request by z3ugma**
Resolves #261 

### Description
Creates `db/seeds/dev.rb` with `CoreBoxItem`s based on realistic data provided by Voices of Consent.

Inspired by https://haughtcodeworks.com/blog/software-development/different-seeds-for-different-needs/ for a multi-environment seed structure. 

### Type of change

- Documentation update
- Developer happiness (seeds file)

### How Has This Been Tested?
Manually running `rake db:reset db:seed:dev`

### CODE REVIEW

**Review by maebeale — COMMENTED** [review]
Thanks @z3ugma ! I know this is super small, but would you be willing to make the dev seeds reference the dev namespace so we are keeping all the development-related stuff under one namespace, if not one file? 

We had wanted to instruct users to use the `dev:setup` (instead of db:reset) in the README, but maybe I'm missing something about why you were recommending db:reset there?

**Comment by maebeale** [comment]
TOTALLY excited about this PR, @z3ugma ! Definitely a welcomed addition!!!

**Comment by z3ugma** [comment]
You can run `rake dev:setup` for your initial up - here's what that task will now run after this PR:
` task setup: ["config/database.yml", "db:setup", "db:seed:dev"]`
so it runs all 3 of those steps - first create the database.yml file, then setup the db, then seed it with `dev`. That's defined at :
https://github.com/rubyforgood/voices-of-consent/pull/273/files#diff-d36dd0926c5b89774b950af54144b8b2R8

Once you've got the dev environment up and running, let's say you wanted to reset your DB and start fresh. You could run `rake db:reset` and that will incorporate the generic `seeds.rb` file. My addition to the README is meant to cover that case where you're _re_-seeding the DB, not initial setup. I'm happy to modify the README to make that clearer if you'd like

**Comment by z3ugma** [comment]
Also let me know if you want to keep with your first recommendation after my explanation - I'm fine with moving it under the `dev` namespace instead. The `seeds` namespace is designed to be able to add additional seeds: `demo`, or `performance` e.g.

**Comment by maebeale** [comment]
But the `db:reset` won't capture the `database.yml`, so that's why we did `dev:setup`. We purposefully made it a different namespace so people would take note that we're definitely doing something out of the ordinary. If we introduce `db:reset` as even a post dev:setup option, then people might skip dev:setup in the first place (being that most people skim-read docs, if they refer to them at all!), but, yeah, probably good to explicitly describe both situations and why we added the dev namespace. Hear ya on seeds namespace -- I think we should go with what you've got. Thank  you for the follow-up!

**Comment by maebeale** [comment]
Would you be willing to add a little more text in the README re the above thread? That way it's super clear the db namespace is only being used after we're started.

**Comment by z3ugma** [comment]
Updated `README` so that no one is ever encouraged to use db:reset, only dev:setup or db:seed:dev after they've run dev:setup

**Review by maebeale — APPROVED** [review]
Thanks so much, @z3ugma !!!

**Pull request merged**
