### PR TITLE
176 message log fields

### LINKED ISSUE #176: MessageLog needs more fields
MessageLog needs:

- `subject_line` so we can better log messages sent out
- `message_type` so we can track when follow-up stage is completed (Type examples include: followup_email)
- `message_channel` (e.g. `autoemail, email, text, call, mail`)

Please find where we are creating MessageLogs and update those to populate the fields above.

### PR DESCRIPTION
**Pull request by MxOliver**
Resolves #176  

### Description
Added new fields to message_log (subject_line, message_type, and message_channel) and wrote a new model test for message_log 

No new dependencies, just new data migrations. 

Include anything else we should know about. -->

The test I wrote is passing but a lot of other tests aren't, will work on that later and try to get everything green again

### Type of change

* New feature (non-breaking change which adds functionality)

### How Has This Been Tested?

`spec/models/message_log_spec.rb` tests that the model responds to the new attributes added

you will just need to pull the changes, run a db:migration, and then run `rspec spec/models/message_log_spec.rb` to verify

### CODE REVIEW

**Comment by maebeale** [comment]
Thanks, @mxoliver! Did you check if we're creating logs yet? We want to create a log every time we send an autoemail (and can retain better records now that we have these new fields).

**Comment by MxOliver** [comment]
Oh no I didn't check, I will take a look and set it up if not

Edit: So we are creating message logs every time a new volunteer signs up and we send out the welcome_email. I am not familiar enough with the project plan yet to know if we are sending autoemails out in other cases but if you know of any I can set it up. I hope to make it to one of the hack nights soon so I can get on the same page in terms of the larger scope

**Comment by maebeale** [comment]
thanks @MxOliver !

Yes, please look for any calls to: `VolunteerMailer` (though I think https://github.com/rubyforgood/voices-of-consent/pull/193/files is the first addition of capacity to these these emails).

The app is pretty email-dependent for all phases of the workflow:
BoxRequest -> BoxReview -> BoxDesign -> BoxAssembly -> BoxShipment -> BoxFollowup

BoxRequest creation should send one through the VolunteerMailer alerting volunteers of the new request, but I believe we'll want to send one to the Requester as well.

**Comment by MxOliver** [comment]
Okay cool I will set that up and commit it to this same PR

**Review by maebeale — APPROVED** [review]

**Pull request merged**
